name: Validate attributes.json

on:
  push:
    paths:
      - 'resources/attributes.json'
      - 'resources/attributes.schema.json'
    branches:
      - '**'
  pull_request:
    paths:
      - 'resources/attributes.json'
      - 'resources/attributes.schema.json'
    branches:
      - '**'
  workflow_dispatch:

jobs:
  validate-json:
    runs-on: ubuntu-latest
    name: Validate attributes.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install .

      - name: Validate JSON
        run: |
          validate-attributes-json --schema resources/attributes.schema.json --json resources/attributes.json